### ISSUE TITLE
How to force the ordering of the sets

### ISSUE THREAD

**Issue by nh13** [jnothman/UpSetPlot#116]

**Comment by jnothman** [comment]
The ordering of the intersections, or the categories??

**Comment by nh13** [comment]
The categories.

**Comment by jnothman** [comment]
Order them in advance, then use `sort_categories_by=None`?

**Comment by abubelinha** [comment]
@jnothman First of all, thank you so much for this wonderful package!

When you say "order in advance", do you mean ordering the dataframe output of the `from_contents()` function?
That's what I am using later as input for `UpSet()`

Looks like it is a dataframe with a single '`id`' column, with a multiindex based on the categories.
So you mean I should change the order of categories in this index [as explained here](https://stackoverflow.com/questions/54040923/change-order-of-pandas-multiindex/54041000#54041000)?

The point is my categories are already sorted, but I am needing to reverse them because it is a bit antinatural for me that categories are plotted in reverse order by default.
I mean, when `orientation=horizontal `(default), the categories (`sort_categories_by=None`) are sort from bottom to top.
I would expect to see them from top to bottom.

If `orientation` is set to `vertical`, then categories are sort from left to right (which looks natural to me).

But for the horizontal I would suggest to change it. 
Or at least, [adding an option](https://upsetplot.readthedocs.io/en/stable/api.html#upsetplot.UpSet) for doing this, i.e. sort_categories_by:'reverse'

Thanks a lot in advance
@abubelinha
