### ISSUE TITLE
ValuError sum_over must be False

### ISSUE THREAD

**Issue by vendig** [jnothman/UpSetPlot#54]
Hi,
I am encountering a problem when trying to use upsetplot.
When I am running:
from upsetplot import from_memberships
example = from_memberships(
[[],
['set2'],
['set1'],
['set1', 'set2'],
['set0'],
['set0', 'set2'],
['set0', 'set1'],
['set0', 'set1', 'set2'],
],
data=[56,283,1279,5882,24,90,429,1957])

and then
from upsetplot import plot
plot(example) 

An error appears:
ValueError: sum_over must be False or a column name when a DataFrame is input

When running example = generate_data(aggregated=True), plotting is working fine.
Please let me know, what the issue might be.

Thank you,
Vendi

**Comment by jnothman** [comment]
Thanks for the report. I'll try look into it soon.

**Comment by jnothman** [comment]
The issue is that plot now supports `DataFrame`s as input, not just `Series`, but needs you to specify whether you want to *count* the quantity of rows in each subset, or *sum over* some field. `from_memberships` is returning a DataFrame because it doesn't recognise that `data` is equivalent to a Series. I think I need to fix this to make `from_memberships` recognise that `data` is 1d and return a `Series`. Thanks for the report.

**Comment by jnothman** [comment]
Maybe I should also find a way to make passing in a data frame friendlier...
